application: portalz-a
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /.*
  script: portalz.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
