application: portalz-a
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: static/js
  secure: optional
- url: /css
  static_dir: static/css
  secure: optional
- url: /img
  static_dir: static/img
  secure: optional
- url: /.*
  script: portalz.application
  secure: optional

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- appstats: on
